name: 'AdvancedWorldGenerator'
version: ${project.version}
main: me.marc_val_96.bukkit.advancedworldgenerator.AWGPlugin
load: 'STARTUP'
authors:
  - Marc_val_96

commands:
  awg:
    description: AdvancedWorldGenerator commands
    usage: |
      "/<command> <check> [world] - Checks awg is enable for this world."'"
      "/<command> <reload> [world] - Reload config"
      "/<command> <biome> [-f] [-w] - Show current biome information"
    aliases: [advancedworldgenerator]
permissions:
  awg.*:
    default: false
    children:
      awg.cmd.*: true
  awg.cmd.*:
    default: false
    children:
      awg.cmd.biome: true
      awg.cmd.check: true
      awg.cmd.help: true
      awg.cmd.list: true
      awg.cmd.map: true
      awg.cmd.reload: true
      awg.cmd.spawn: true
  awg.cmd.biome:
    default: op
    description: 'show chunk biome and block stats'
  awg.cmd.check:
    default: op
    description: 'check/create awg settings for world'
  awg.cmd.help:
    default: op
    description: 'show help'
  awg.cmd.list:
    default: op
    description: 'list bo2 objects'
  awg.cmd.map:
    default: op
    description: 'generate biome map image'
  awg.cmd.reload:
    default: op
    description: 'reload world settings'
  awg.cmd.spawn:
    default: op
    description: 'spawn bo2 where you look'